// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oqvqctgewpbzgbawyosj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9xdnFjdGdld3BiemdiYXd5b3NqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0NTgyNDcsImV4cCI6MjA3MTAzNDI0N30.sKbyfH_zvzxT4KaZVggORzVJzR2HGV1mkNXx0l2F4Uk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});